update=10/24/2017 11:18:57 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=E:/Program Files/KiCad/share/kicad/library/kicad-library/library
[eeschema/libraries]
LibName1=power
LibName2=device
LibName3=transistors
LibName4=conn
LibName5=linear
LibName6=regul
LibName7=74xx
LibName8=cmos4000
LibName9=adc-dac
LibName10=memory
LibName11=xilinx
LibName12=microcontrollers
LibName13=dsp
LibName14=microchip
LibName15=analog_switches
LibName16=motorola
LibName17=texas
LibName18=intel
LibName19=audio
LibName20=interface
LibName21=digital-audio
LibName22=philips
LibName23=display
LibName24=cypress
LibName25=siliconi
LibName26=opto
LibName27=atmel
LibName28=contrib
LibName29=valves
LibName30=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ac-dc
LibName31=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/adc-dac
LibName32=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Altera
LibName33=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/analog_devices
LibName34=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/analog_switches
LibName35=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/atmel
LibName36=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/audio
LibName37=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Battery_Management
LibName38=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/bbd
LibName39=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/bosch
LibName40=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/brooktre
LibName41=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Connector
LibName42=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/contrib
LibName43=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/cypress
LibName44=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/dc-dc
LibName45=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/device
LibName46=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/digital-audio
LibName47=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Diode
LibName48=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Display
LibName49=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/driver_gate
LibName50=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/dsp
LibName51=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/DSP_Microchip_DSPIC33
LibName52=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/elec-unifil
LibName53=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ESD_Protection
LibName54=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Espressif
LibName55=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/FPGA_Actel
LibName56=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ftdi
LibName57=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/gennum
LibName58=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Graphic
LibName59=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/hc11
LibName60=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/infineon
LibName61=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/intel
LibName62=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/interface
LibName63=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/intersil
LibName64=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ir
LibName65=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Lattice
LibName66=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/LED
LibName67=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/LEM
LibName68=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/linear
LibName69=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_74xgxx
LibName70=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_74xx
LibName71=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_CMOS_4000
LibName72=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_CMOS_IEEE
LibName73=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/logic_programmable
LibName74=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_TTL_IEEE
LibName75=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/maxim
LibName76=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC10
LibName77=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC12
LibName78=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC16
LibName79=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC18
LibName80=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC24
LibName81=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC32
LibName82=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_Kinetis
LibName83=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_LPC
LibName84=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_S08
LibName85=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_ST_STM8
LibName86=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_ST_STM32
LibName87=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Texas_MSP430
LibName88=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Mechanical
LibName89=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/memory
LibName90=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/microchip
LibName91=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/microcontrollers
LibName92=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/modules
LibName93=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Motor
LibName94=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/motor_drivers
LibName95=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/motorola
LibName96=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/nordicsemi
LibName97=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/nxp
LibName98=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/onsemi
LibName99=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/opto
LibName100=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Oscillators
LibName101=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/philips
LibName102=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/power
LibName103=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Power_Management
LibName104=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/powerint
LibName105=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/pspice
LibName106=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/references
LibName107=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/regul
LibName108=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Relay
LibName109=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/rfcom
LibName110=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/RFSolutions
LibName111=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Sensor_Current
LibName112=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/sensors
LibName113=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/silabs
LibName114=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/siliconi
LibName115=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/supertex
LibName116=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Switch
LibName117=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/texas
LibName118=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Transformer
LibName119=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Transistor
LibName120=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/triac_thyristor
LibName121=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Valve
LibName122=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/video
LibName123=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/wiznet
LibName124=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Worldsemi
LibName125=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Xicor
LibName126=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/xilinx
LibName127=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/zetex
LibName128=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Zilog
LibName129=E:/Program Files/KiCad/share/kicad/library/MyLib
[general]
version=1
