update=10/26/2017 10:33:27 PM
version=1
last_client=kicad
[pcbnew]
version=1
LastNetListRead=
UseCmpFile=1
PadDrill=0.600000000000
PadDrillOvalY=0.600000000000
PadSizeH=1.500000000000
PadSizeV=1.500000000000
PcbTextSizeV=1.500000000000
PcbTextSizeH=1.500000000000
PcbTextThickness=0.300000000000
ModuleTextSizeV=1.000000000000
ModuleTextSizeH=1.000000000000
ModuleTextSizeThickness=0.150000000000
SolderMaskClearance=0.000000000000
SolderMaskMinWidth=0.000000000000
DrawSegmentWidth=0.200000000000
BoardOutlineThickness=0.100000000000
ModuleOutlineThickness=0.150000000000
[cvpcb]
version=1
NetIExt=net
[eeschema]
version=1
LibDir=E:/Program Files/KiCad/share/kicad/library/kicad-library/library
[eeschema/libraries]
LibName1=DualBand-rescue
LibName2=power
LibName3=device
LibName4=transistors
LibName5=conn
LibName6=linear
LibName7=regul
LibName8=74xx
LibName9=cmos4000
LibName10=adc-dac
LibName11=memory
LibName12=xilinx
LibName13=microcontrollers
LibName14=dsp
LibName15=microchip
LibName16=analog_switches
LibName17=motorola
LibName18=texas
LibName19=intel
LibName20=audio
LibName21=interface
LibName22=digital-audio
LibName23=philips
LibName24=display
LibName25=cypress
LibName26=siliconi
LibName27=opto
LibName28=atmel
LibName29=contrib
LibName30=valves
LibName31=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ac-dc
LibName32=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/adc-dac
LibName33=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Altera
LibName34=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/analog_devices
LibName35=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/analog_switches
LibName36=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/atmel
LibName37=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/audio
LibName38=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Battery_Management
LibName39=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/bbd
LibName40=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/bosch
LibName41=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/brooktre
LibName42=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Connector
LibName43=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/contrib
LibName44=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/cypress
LibName45=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/dc-dc
LibName46=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/device
LibName47=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/digital-audio
LibName48=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Diode
LibName49=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Display
LibName50=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/driver_gate
LibName51=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/dsp
LibName52=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/DSP_Microchip_DSPIC33
LibName53=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/elec-unifil
LibName54=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ESD_Protection
LibName55=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Espressif
LibName56=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/FPGA_Actel
LibName57=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ftdi
LibName58=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/gennum
LibName59=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Graphic
LibName60=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/hc11
LibName61=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/infineon
LibName62=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/intel
LibName63=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/interface
LibName64=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/intersil
LibName65=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/ir
LibName66=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Lattice
LibName67=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/LED
LibName68=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/LEM
LibName69=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/linear
LibName70=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_74xgxx
LibName71=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_74xx
LibName72=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_CMOS_4000
LibName73=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_CMOS_IEEE
LibName74=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/logic_programmable
LibName75=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Logic_TTL_IEEE
LibName76=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/maxim
LibName77=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC10
LibName78=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC12
LibName79=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC16
LibName80=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC18
LibName81=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC24
LibName82=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Microchip_PIC32
LibName83=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_Kinetis
LibName84=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_LPC
LibName85=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_NXP_S08
LibName86=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_ST_STM8
LibName87=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_ST_STM32
LibName88=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/MCU_Texas_MSP430
LibName89=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Mechanical
LibName90=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/memory
LibName91=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/microchip
LibName92=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/microcontrollers
LibName93=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/modules
LibName94=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Motor
LibName95=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/motor_drivers
LibName96=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/motorola
LibName97=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/nordicsemi
LibName98=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/nxp
LibName99=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/onsemi
LibName100=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/opto
LibName101=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Oscillators
LibName102=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/philips
LibName103=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/power
LibName104=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Power_Management
LibName105=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/powerint
LibName106=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/pspice
LibName107=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/references
LibName108=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/regul
LibName109=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Relay
LibName110=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/rfcom
LibName111=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/RFSolutions
LibName112=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Sensor_Current
LibName113=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/sensors
LibName114=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/silabs
LibName115=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/siliconi
LibName116=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/supertex
LibName117=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Switch
LibName118=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/texas
LibName119=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Transformer
LibName120=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Transistor
LibName121=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/triac_thyristor
LibName122=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Valve
LibName123=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/video
LibName124=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/wiznet
LibName125=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Worldsemi
LibName126=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Xicor
LibName127=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/xilinx
LibName128=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/zetex
LibName129=E:/Program Files/KiCad/share/kicad/library/kicad-library/library/Zilog
LibName130=E:/Program Files/KiCad/share/kicad/library/MyLib
[general]
version=1
